[package]
name = "crypto-derive"
version = "0.1.0"
description = "Custom derives for `crypto`"
edition = "2018"

[lib]
proc_macro = true

[dependencies]
syn = { version = "0.15.26", features = ["derive"] }
quote = "0.6.11"
