// This file is generated by rust-protobuf 2.7.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `validator_change.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_7_0;

#[derive(PartialEq,Clone,Default)]
pub struct ValidatorChangeEventWithProof {
    // message fields
    pub ledger_info_with_sigs: ::protobuf::SingularPtrField<super::ledger_info::LedgerInfoWithSignatures>,
    pub event_with_proof: ::protobuf::SingularPtrField<super::events::EventWithProof>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ValidatorChangeEventWithProof {
    fn default() -> &'a ValidatorChangeEventWithProof {
        <ValidatorChangeEventWithProof as ::protobuf::Message>::default_instance()
    }
}

impl ValidatorChangeEventWithProof {
    pub fn new() -> ValidatorChangeEventWithProof {
        ::std::default::Default::default()
    }

    // .types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;


    pub fn get_ledger_info_with_sigs(&self) -> &super::ledger_info::LedgerInfoWithSignatures {
        self.ledger_info_with_sigs.as_ref().unwrap_or_else(|| super::ledger_info::LedgerInfoWithSignatures::default_instance())
    }
    pub fn clear_ledger_info_with_sigs(&mut self) {
        self.ledger_info_with_sigs.clear();
    }

    pub fn has_ledger_info_with_sigs(&self) -> bool {
        self.ledger_info_with_sigs.is_some()
    }

    // Param is passed by value, moved
    pub fn set_ledger_info_with_sigs(&mut self, v: super::ledger_info::LedgerInfoWithSignatures) {
        self.ledger_info_with_sigs = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_ledger_info_with_sigs(&mut self) -> &mut super::ledger_info::LedgerInfoWithSignatures {
        if self.ledger_info_with_sigs.is_none() {
            self.ledger_info_with_sigs.set_default();
        }
        self.ledger_info_with_sigs.as_mut().unwrap()
    }

    // Take field
    pub fn take_ledger_info_with_sigs(&mut self) -> super::ledger_info::LedgerInfoWithSignatures {
        self.ledger_info_with_sigs.take().unwrap_or_else(|| super::ledger_info::LedgerInfoWithSignatures::new())
    }

    // .types.EventWithProof event_with_proof = 2;


    pub fn get_event_with_proof(&self) -> &super::events::EventWithProof {
        self.event_with_proof.as_ref().unwrap_or_else(|| super::events::EventWithProof::default_instance())
    }
    pub fn clear_event_with_proof(&mut self) {
        self.event_with_proof.clear();
    }

    pub fn has_event_with_proof(&self) -> bool {
        self.event_with_proof.is_some()
    }

    // Param is passed by value, moved
    pub fn set_event_with_proof(&mut self, v: super::events::EventWithProof) {
        self.event_with_proof = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_event_with_proof(&mut self) -> &mut super::events::EventWithProof {
        if self.event_with_proof.is_none() {
            self.event_with_proof.set_default();
        }
        self.event_with_proof.as_mut().unwrap()
    }

    // Take field
    pub fn take_event_with_proof(&mut self) -> super::events::EventWithProof {
        self.event_with_proof.take().unwrap_or_else(|| super::events::EventWithProof::new())
    }
}

impl ::protobuf::Message for ValidatorChangeEventWithProof {
    fn is_initialized(&self) -> bool {
        for v in &self.ledger_info_with_sigs {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.event_with_proof {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.ledger_info_with_sigs)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.event_with_proof)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.ledger_info_with_sigs.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.event_with_proof.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.ledger_info_with_sigs.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.event_with_proof.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ValidatorChangeEventWithProof {
        ValidatorChangeEventWithProof::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::ledger_info::LedgerInfoWithSignatures>>(
                    "ledger_info_with_sigs",
                    |m: &ValidatorChangeEventWithProof| { &m.ledger_info_with_sigs },
                    |m: &mut ValidatorChangeEventWithProof| { &mut m.ledger_info_with_sigs },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::events::EventWithProof>>(
                    "event_with_proof",
                    |m: &ValidatorChangeEventWithProof| { &m.event_with_proof },
                    |m: &mut ValidatorChangeEventWithProof| { &mut m.event_with_proof },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ValidatorChangeEventWithProof>(
                    "ValidatorChangeEventWithProof",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ValidatorChangeEventWithProof {
        static mut instance: ::protobuf::lazy::Lazy<ValidatorChangeEventWithProof> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ValidatorChangeEventWithProof,
        };
        unsafe {
            instance.get(ValidatorChangeEventWithProof::new)
        }
    }
}

impl ::protobuf::Clear for ValidatorChangeEventWithProof {
    fn clear(&mut self) {
        self.ledger_info_with_sigs.clear();
        self.event_with_proof.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ValidatorChangeEventWithProof {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ValidatorChangeEventWithProof {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x16validator_change.proto\x12\x05types\x1a\x0cevents.proto\x1a\x11led\
    ger_info.proto\"\xb4\x01\n\x1dValidatorChangeEventWithProof\x12R\n\x15le\
    dger_info_with_sigs\x18\x01\x20\x01(\x0b2\x1f.types.LedgerInfoWithSignat\
    uresR\x12ledgerInfoWithSigs\x12?\n\x10event_with_proof\x18\x02\x20\x01(\
    \x0b2\x15.types.EventWithProofR\x0eeventWithProofb\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
